spring:
    application.name: soundcloud
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/soundcloud
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    output:
        ansi:
            enabled: always

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================
jhipster:
    security:
        authentication:
            jwt:
                base64-secret: MzFhMWIyNDQxYTljM2FmNjE4NWFkNWI4OTIxOWM0NTg4ZjYxYWFmOWY3ZWIwMmRjZTExNGYxMjMxMmIxNGJhOWQ5ZWU0NmM1Y2Q1ZmVmOTliNTc2Njc1ZjdhYmZkYWZjZGMwYThjNGM4MzJhNDk3ZmU5M2Q3ZjA2NzcxM2U3OTU=
                access-token-validity-in-seconds: 8640000
