spring:
    application.name: soundcloud
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/soundcloud
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    output:
        ansi:
            enabled: always
    data:
        web:
            pageable:
                one-indexed-parameters: true
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================
jhipster:
    security:
        authentication:
            jwt:
                base64-secret: MzFhMWIyNDQxYTljM2FmNjE4NWFkNWI4OTIxOWM0NTg4ZjYxYWFmOWY3ZWIwMmRjZTExNGYxMjMxMmIxNGJhOWQ5ZWU0NmM1Y2Q1ZmVmOTliNTc2Njc1ZjdhYmZkYWZjZGMwYThjNGM4MzJhNDk3ZmU5M2Q3ZjA2NzcxM2U3OTU=
                access-token-validity-in-seconds: 300
                refresh-token-validity-in-seconds: 8640000
    upload-file:
        base-path: file:///E:/SelfLearingIT/PersonalProject/00-java-spring-restful-nextjs-soundcloud/upload/